// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: companies.sql

package db

import (
	"context"
)

const insertCompany = `-- name: InsertCompany :exec
INSERT INTO companies (
  id,
  bank_id,
  bill_id,
  payment_id,
  deadline_id,
  company_name,
  phone_num
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertCompanyParams struct {
	ID          int32  `json:"id"`
	BankID      int32  `json:"bank_id"`
	BillID      int32  `json:"bill_id"`
	PaymentID   int32  `json:"payment_id"`
	DeadlineID  int32  `json:"deadline_id"`
	CompanyName string `json:"company_name"`
	PhoneNum    int32  `json:"phone_num"`
}

func (q *Queries) InsertCompany(ctx context.Context, arg InsertCompanyParams) error {
	_, err := q.db.ExecContext(ctx, insertCompany,
		arg.ID,
		arg.BankID,
		arg.BillID,
		arg.PaymentID,
		arg.DeadlineID,
		arg.CompanyName,
		arg.PhoneNum,
	)
	return err
}
