// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
)

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (
  id,
  username,
  email,
  password_hash
)
VALUES ($1, $2, $3, $4)
`

type InsertUserParams struct {
	ID           int32  `json:"id"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	return err
}
