// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Bank struct {
	ID   int32
	Name string
}

type Bill struct {
	ID           int32
	CompanyID    int32
	BankID       int32
	Amount       int32
	PaymentLimit int32
	PaymentDate  time.Time
	PaidAt       pgtype.Timestamptz
	Description  pgtype.Text
	CreatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Company struct {
	ID       int32
	Name     string
	CreateAt pgtype.Timestamp
}

type User struct {
	ID           int32
	Name         string
	Email        string
	PasswordHash pgtype.Text
	DeletedAt    pgtype.Timestamptz
}
