// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bills.sql

package db

import (
	"context"
	"database/sql"
)

const insertBill = `-- name: InsertBill :exec
INSERT INTO bills (
  id,
  company_id,
  is_paid,
  description
)
VALUES ($1, $2, $3, $4)
`

type InsertBillParams struct {
	ID          int32          `json:"id"`
	CompanyID   int32          `json:"company_id"`
	IsPaid      bool           `json:"is_paid"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) InsertBill(ctx context.Context, arg InsertBillParams) error {
	_, err := q.db.ExecContext(ctx, insertBill,
		arg.ID,
		arg.CompanyID,
		arg.IsPaid,
		arg.Description,
	)
	return err
}
