// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deadlines.sql

package db

import (
	"context"
)

const insertDeadline = `-- name: InsertDeadline :exec
INSERT INTO deadlines (
    id, 
    payment_date
)
VALUES ($1, $2)
`

type InsertDeadlineParams struct {
	ID          int32  `json:"id"`
	PaymentDate string `json:"payment_date"`
}

func (q *Queries) InsertDeadline(ctx context.Context, arg InsertDeadlineParams) error {
	_, err := q.db.ExecContext(ctx, insertDeadline, arg.ID, arg.PaymentDate)
	return err
}
