// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"
)

func (s PaymentDate) Validate() error {
	switch s {
	case "current_month_end":
		return nil
	case "next_month_15":
		return nil
	case "next_month_20":
		return nil
	case "next_month_end":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}
