// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// BanksIDGet implements GET /banks/{id} operation.
//
// Get information.
//
// GET /banks/{id}
func (UnimplementedHandler) BanksIDGet(ctx context.Context, params BanksIDGetParams) (r BanksIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// BanksPost implements POST /banks operation.
//
// Create banks.
//
// POST /banks
func (UnimplementedHandler) BanksPost(ctx context.Context, req *CreateBankRequest) (r *Bank, _ error) {
	return r, ht.ErrNotImplemented
}

// BillsGet implements GET /bills operation.
//
// Get bill.
//
// GET /bills
func (UnimplementedHandler) BillsGet(ctx context.Context, params BillsGetParams) (r *BillListResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// BillsIDDelete implements DELETE /bills/{id} operation.
//
// Delete bill.
//
// DELETE /bills/{id}
func (UnimplementedHandler) BillsIDDelete(ctx context.Context, params BillsIDDeleteParams) error {
	return ht.ErrNotImplemented
}

// BillsIDGet implements GET /bills/{id} operation.
//
// Get  direct bill.
//
// GET /bills/{id}
func (UnimplementedHandler) BillsIDGet(ctx context.Context, params BillsIDGetParams) (r *Bill, _ error) {
	return r, ht.ErrNotImplemented
}

// BillsIDPaymentStatusPatch implements PATCH /bills/{id}/payment-status operation.
//
// Chenge payment-status.
//
// PATCH /bills/{id}/payment-status
func (UnimplementedHandler) BillsIDPaymentStatusPatch(ctx context.Context, req *UpdatePaymentStatusRequest, params BillsIDPaymentStatusPatchParams) (r *Bill, _ error) {
	return r, ht.ErrNotImplemented
}

// BillsIDPut implements PUT /bills/{id} operation.
//
// Update bill.
//
// PUT /bills/{id}
func (UnimplementedHandler) BillsIDPut(ctx context.Context, req *UpdateBillRequest, params BillsIDPutParams) (r *Bill, _ error) {
	return r, ht.ErrNotImplemented
}

// BillsPost implements POST /bills operation.
//
// Create bill.
//
// POST /bills
func (UnimplementedHandler) BillsPost(ctx context.Context, req *CreateBillRequest) (r BillsPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CompaniesIDDelete implements DELETE /companies/{id} operation.
//
// Delete.
//
// DELETE /companies/{id}
func (UnimplementedHandler) CompaniesIDDelete(ctx context.Context, params CompaniesIDDeleteParams) error {
	return ht.ErrNotImplemented
}

// CompaniesIDGet implements GET /companies/{id} operation.
//
// Get company information.
//
// GET /companies/{id}
func (UnimplementedHandler) CompaniesIDGet(ctx context.Context, params CompaniesIDGetParams) (r *Company, _ error) {
	return r, ht.ErrNotImplemented
}

// CompaniesIDPut implements PUT /companies/{id} operation.
//
// Update.
//
// PUT /companies/{id}
func (UnimplementedHandler) CompaniesIDPut(ctx context.Context, req *UpdateCompanyRequest, params CompaniesIDPutParams) (r *Company, _ error) {
	return r, ht.ErrNotImplemented
}

// CompaniesPost implements POST /companies operation.
//
// Create company.
//
// POST /companies
func (UnimplementedHandler) CompaniesPost(ctx context.Context, req *CreateCompanyRequest) (r *Company, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersGet implements GET /users operation.
//
// Get user.
//
// GET /users
func (UnimplementedHandler) UsersGet(ctx context.Context, req *GetUserRequest) (r UsersGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersIDDelete implements DELETE /users/{id} operation.
//
// Delete user.
//
// DELETE /users/{id}
func (UnimplementedHandler) UsersIDDelete(ctx context.Context, params UsersIDDeleteParams) (r UsersIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersIDGet implements GET /users/{id} operation.
//
// Get user.
//
// GET /users/{id}
func (UnimplementedHandler) UsersIDGet(ctx context.Context, params UsersIDGetParams) (r UsersIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersIDPut implements PUT /users/{id} operation.
//
// Update user.
//
// PUT /users/{id}
func (UnimplementedHandler) UsersIDPut(ctx context.Context, req *UpdateUserRequest, params UsersIDPutParams) (r UsersIDPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersPost implements POST /users operation.
//
// Create Users.
//
// POST /users
func (UnimplementedHandler) UsersPost(ctx context.Context, req *CreateUserRequest) (r UsersPostRes, _ error) {
	return r, ht.ErrNotImplemented
}
