// Code generated by ogen, DO NOT EDIT.
package api

type BanksIDGetRes interface {
	banksIDGetRes()
}

type BillsPostRes interface {
	billsPostRes()
}

type UsersGetRes interface {
	usersGetRes()
}

type UsersIDDeleteRes interface {
	usersIDDeleteRes()
}

type UsersIDGetRes interface {
	usersIDGetRes()
}

type UsersIDPutRes interface {
	usersIDPutRes()
}

type UsersPostRes interface {
	usersPostRes()
}
