// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	BanksIDGetOperation                OperationName = "BanksIDGet"
	BanksPostOperation                 OperationName = "BanksPost"
	BillsGetOperation                  OperationName = "BillsGet"
	BillsIDDeleteOperation             OperationName = "BillsIDDelete"
	BillsIDGetOperation                OperationName = "BillsIDGet"
	BillsIDPaymentStatusPatchOperation OperationName = "BillsIDPaymentStatusPatch"
	BillsIDPutOperation                OperationName = "BillsIDPut"
	BillsPostOperation                 OperationName = "BillsPost"
	CompaniesIDDeleteOperation         OperationName = "CompaniesIDDelete"
	CompaniesIDGetOperation            OperationName = "CompaniesIDGet"
	CompaniesIDPutOperation            OperationName = "CompaniesIDPut"
	CompaniesPostOperation             OperationName = "CompaniesPost"
	UsersGetOperation                  OperationName = "UsersGet"
	UsersIDDeleteOperation             OperationName = "UsersIDDelete"
	UsersIDGetOperation                OperationName = "UsersIDGet"
	UsersIDPutOperation                OperationName = "UsersIDPut"
	UsersPostOperation                 OperationName = "UsersPost"
)
