// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Auth implements Auth operation.
//
// Authenticate User (Sign In or Sign Up).
//
// POST /auth
func (UnimplementedHandler) Auth(ctx context.Context, req *AuthReq) (r AuthRes, _ error) {
	return r, ht.ErrNotImplemented
}

// BanksIDGet implements GET /banks/{id} operation.
//
// Get bank information.
//
// GET /banks/{id}
func (UnimplementedHandler) BanksIDGet(ctx context.Context, params BanksIDGetParams) (r BanksIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// BanksPost implements POST /banks operation.
//
// Create bank.
//
// POST /banks
func (UnimplementedHandler) BanksPost(ctx context.Context, req *CreateBankRequest) (r BanksPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// BillsIDDelete implements DELETE /bills/{id} operation.
//
// Delete bill.
//
// DELETE /bills/{id}
func (UnimplementedHandler) BillsIDDelete(ctx context.Context, params BillsIDDeleteParams) (r BillsIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// BillsIDGet implements GET /bills/{id} operation.
//
// Get  bill.
//
// GET /bills/{id}
func (UnimplementedHandler) BillsIDGet(ctx context.Context, params BillsIDGetParams) (r BillsIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// BillsIDPut implements PUT /bills/{id} operation.
//
// Update bill.
//
// PUT /bills/{id}
func (UnimplementedHandler) BillsIDPut(ctx context.Context, req *UpdateBillRequest, params BillsIDPutParams) (r BillsIDPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// BillsPost implements POST /bills operation.
//
// Create bill.
//
// POST /bills
func (UnimplementedHandler) BillsPost(ctx context.Context, req *CreateBillRequest) (r BillsPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// BillsStatementIDPut implements PUT /bills_statement/{id} operation.
//
// Change is_paid of bills.
//
// PUT /bills_statement/{id}
func (UnimplementedHandler) BillsStatementIDPut(ctx context.Context, params BillsStatementIDPutParams) (r BillsStatementIDPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CompaniesIDDelete implements DELETE /companies/{id} operation.
//
// Delete company.
//
// DELETE /companies/{id}
func (UnimplementedHandler) CompaniesIDDelete(ctx context.Context, params CompaniesIDDeleteParams) (r CompaniesIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CompaniesIDGet implements GET /companies/{id} operation.
//
// Get company information.
//
// GET /companies/{id}
func (UnimplementedHandler) CompaniesIDGet(ctx context.Context, params CompaniesIDGetParams) (r CompaniesIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CompaniesIDPut implements PUT /companies/{id} operation.
//
// Update company.
//
// PUT /companies/{id}
func (UnimplementedHandler) CompaniesIDPut(ctx context.Context, params CompaniesIDPutParams) (r CompaniesIDPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CompaniesPost implements POST /companies operation.
//
// Create company.
//
// POST /companies
func (UnimplementedHandler) CompaniesPost(ctx context.Context, req *CreateCompanyRequest) (r CompaniesPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PaydatePaymentDateGet implements GET /paydate/{payment_date} operation.
//
// Get bill by day.
//
// GET /paydate/{payment_date}
func (UnimplementedHandler) PaydatePaymentDateGet(ctx context.Context, params PaydatePaymentDateGetParams) (r PaydatePaymentDateGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersGet implements GET /users operation.
//
// Get users.
//
// GET /users
func (UnimplementedHandler) UsersGet(ctx context.Context, req *GetUserRequest) (r UsersGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersIDDelete implements DELETE /users/{id} operation.
//
// Delete user.
//
// DELETE /users/{id}
func (UnimplementedHandler) UsersIDDelete(ctx context.Context, params UsersIDDeleteParams) (r UsersIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersIDGet implements GET /users/{id} operation.
//
// Get user.
//
// GET /users/{id}
func (UnimplementedHandler) UsersIDGet(ctx context.Context, params UsersIDGetParams) (r UsersIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersIDPut implements PUT /users/{id} operation.
//
// Update user.
//
// PUT /users/{id}
func (UnimplementedHandler) UsersIDPut(ctx context.Context, req *UpdateUserRequest, params UsersIDPutParams) (r UsersIDPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersPost implements POST /users operation.
//
// Create User.
//
// POST /users
func (UnimplementedHandler) UsersPost(ctx context.Context, req *CreateUserRequest) (r UsersPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *InternalServerErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *InternalServerErrorStatusCode) {
	r = new(InternalServerErrorStatusCode)
	return r
}
