openapi: 3.0.3
info:
  title: DueLog API
  description: API
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/dann3256/DueLog

servers:
  - url: http://localhost:8080

  
paths:
  /users:
    post:
      summary: create Users
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users/{id}: 
    get:
      summary: get user
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: user information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: update user
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: error

    delete:
      summary: delete user
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: success
        '404':
          description: error

  
  /banks:
    post:
      summary: create banks
      tags:
        - Banks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBankRequest'
      responses:
        '201':
          description: 銀行作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bank'
   
  /banks/{id}:
    get:
      summary: get information
      tags:
        - Banks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: banks information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bank'
        '404':
          description: error

    

  /companies:
    post:
      summary: create company
      tags:
        - Companies
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCompanyRequest'
      responses:
        '201':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
   

  /companies/{id}:
    get:
      summary: get company information
      tags:
        - Companies
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'

    put:
      summary: update
      tags:
        - Companies
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCompanyRequest'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'

    delete:
      summary: delete
      tags:
        - Companies
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: success


  /bills:
    get:
      summary: 請求書一覧取得（振込日別表示対応）
      tags:
        - Bills
      parameters:
        - name: payment_period
          in: query
          description: 振込期限でフィルタ（current_month_end, next_month_15, next_month_20, next_month_end）
          schema:
            type: string
            enum: [current_month_end, next_month_15, next_month_20, next_month_end]
        - name: is_paid
          in: query
          description: 支払済みステータスでフィルタ
          schema:
            type: boolean
      responses:
        '200':
          description: 請求書一覧
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillListResponse'

    post:
      summary: create bills
      tags:
        - Bills
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBillRequest'
      responses:
        '201':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
        '400':
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillValidationResponse'

  /bills/{id}:
    get:
      summary: all information
      tags:
        - Bills
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'

    put:
      summary: update bill
      tags:
        - Bills
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBillRequest'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'

    delete:
      summary: delete bill
      tags:
        - Bills
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: 削除成功

  /bills/{id}/payment-status:
    patch:
      summary: update status
      tags:
        - Bills
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePaymentStatusRequest'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'

  /bills/summary:
    get:
      summary: summary
      tags:
        - Bills
      responses:
        '200':
          description: 振込日別にグループ化された請求書サマリー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillSummaryResponse'
  
tags:
  - name: Users
    description: ユーザー管理
  - name: Banks
    description: 銀行管理
  - name: Companies
    description: 会社管理
  - name: Bills
    description: 請求書（振込情報）管理