openapi: 3.0.3
info:
  title: DueLog API
  description: API
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/dann3256/DueLog

servers:
  - url: http://localhost:8080

paths:
# user-api
  /users:
    post:
      summary: create User
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/requestBodies.yaml#/components/requestBodies/CreateUserRequest"
      responses:
        "201":
          description: User creation was successful
          content:
            application/json:
              schema:
                $ref: "./components/responseBodies.yaml#/components/responses/UserCreated"
        "404":
          description: error
    get:
      summary: get users
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/requestBodies.yaml#/components/requestBodies/GetUserRequest"
      responses:
        "201":
          description: obtain user information was success
          content:
            application/json:
              schema:
                $ref: "./components/responseBodies.yaml#/components/responses/UserObtained"
        "400":
          description: error

  /users/{id}:
    get:
      summary: get user
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "./components/schema.yaml#/components/responses/User/properties/id"
      responses:
        "200":
          description: obtain user information was success
          content:
            application/json:
              schema:
                $ref: "./components/responseBodies.yaml#/components/responses/UserUpdated"
        "404":
          description: error

    put:
      summary: update user
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/requestBodies.yaml#/components/requestBodies/UpdateUserRequest"
      responses:
        "200":
          description: update was success
          content:
            application/json:
              schema:
                $ref: "./components/responseBodies.yaml#/components/responses/UserUpdated"
        "404":
          description: error

    delete:
      summary: delete user
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: delete was success
        "404":
          description: error

# bank-api
  /banks:
    post:
      summary: create bank
      tags:
        - Banks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/requestBodies.yaml#/components/requestBodies/CreateBankRequest"
      responses:
        "201":
          description: creation bank was success
          content:
            application/json:
              schema:
                $ref: "./components/responseBodies.yaml#/components/responses/BankCreated"
        "404":
          description: error

  /banks/{id}:
    get:
      summary: get bank information
      tags:
        - Banks
      parameters:
        - name: id
          in: path
          required: true
          schema:
           $ref: "./components/schema.yaml#/components/responses/Bank/properties/id"
      responses:
        "200":
          description: obtain bank information was success
          content:
            application/json:
              schema:
                $ref: "./components/responseBodies.yaml#/components/responses/BankObtained"
        "404":
          description: error

# company-api
  /companies:
    post:
      summary: create company
      tags:
        - Companies
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/requestBodies.yaml#/components/requestBodies/CreateCompanyRequest"
      responses:
        "201":
          description: creation companies was success
          content:
            application/json:
              schema:
                $ref: "./components/responseBodies.yaml#/components/responses/CompanyCreated"
        "404":
          description: error

  /companies/{id}:
    get:
      summary: get company information
      tags:
        - Companies
      parameters:
        - name: id
          in: path
          required: true
          schema:
           $ref: "./components/schema.yaml#/components/responses/Company/properties/id"
      responses:
        "200":
          description: obtain companies was success
          content:
            application/json:
              schema:
                $ref: "./components/responseBodies.yaml#/components/responses/CompanyObtained"
        "404":
          description: error

    put:
      summary: update company
      tags:
        - Companies
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: update companies was success
          content:
            application/json:
              schema:
                $ref: "./components/responseBodies.yaml#/components/responses/CompanyUpdated"
        "404":
          description: error

    delete:
      summary: delete company
      tags:
        - Companies
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: delete companies was success
        "404":
          description: error
          
# bill-api
  /bills:
     post:
      summary: create bill
      tags:
        - Bills
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/requestBodies.yaml#/components/requestBodies/CreateBillRequest"
        "201":
          description: creation bill was success
          content:
            application/json:
              schema:
                $ref: "./components/responseBodies.yaml#/components/responses/BillCreated"
        "404":
          description: error

   
  /bills/{id}:
    get:
      summary: get  bill
      tags:
        - Bills
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "./components/schema.yaml#/components/responses/Bill/properties/id"
      responses:
        "200":
          description: obtain direct bill information was success
          content:
            application/json:
              schema:
                $ref: "./components/responseBodies.yaml#/components/responses/BillObtained"
        "404":
          description: error

    put:
      summary: update bill
      tags:
        - Bills
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/requestBodies.yaml#/components/requestBodies/UpdateBillRequest"
      responses:
        "200":
          description: update bill was success
          content:
            application/json:
              schema:
                $ref: "./components/responseBodies.yaml#/components/responses/BillUpdated"
        "404":
          description: error
        
    
    

    delete:
      summary: delete bill
      tags:
        - Bills
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: delete bill was success
      "404":
          description: error

  /bills/{payment_date}:
    get:
      summary: get bill by day
      tags:
        - Bills
      parameters:
        - name: payment_id
          in: path
          required: true
          schema:
           $ref: "./components/schema.yaml#/components/responses/Bill/properties/payment_date"
      
      responses:
        "200":
          description: changing status was success
          content:
            application/json:
              schema:
                $ref: "./components/responseBodies.yaml#/components/responses/BillObtained"
        "404":
          description: error

  /bills_statement/{id}:
   put:
      summary: change is_paid of bills
      tags:
        - Bills
      parameters:
        - name: id
          in: path
          required: true
          schema:
           $ref: "./components/schema.yaml#/components/responses/Bill/properties/id"
      
      responses:
        "200":
          description: change is_paid was success
          
        "404":
          description: error
   
tags:
  - name: Users
    description: ユーザー管理
  - name: Banks
    description: 銀行管理
  - name: Companies
    description: 会社管理
  - name: Bills
    description: 請求書（振込情報）管理
